language: go
sudo: false
go:
  - 1.11.x
before_install:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
jobs:
  include:
    - script: make all
    - stage: Run Test Coverage
      script: make cover
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Build Release
      script:
        - make release
        - echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file:
          - cross/bane-darwin-amd64
          - cross/bane-darwin-amd64.md5
          - cross/bane-darwin-amd64.sha256
          - cross/bane-darwin-386
          - cross/bane-darwin-386.md5
          - cross/bane-darwin-386.sha256
          - cross/bane-freebsd-amd64
          - cross/bane-freebsd-amd64.md5
          - cross/bane-freebsd-amd64.sha256
          - cross/bane-freebsd-386
          - cross/bane-freebsd-386.md5
          - cross/bane-freebsd-386.sha256
          - cross/bane-linux-arm
          - cross/bane-linux-arm.md5
          - cross/bane-linux-arm.sha256
          - cross/bane-linux-arm64
          - cross/bane-linux-arm64.md5
          - cross/bane-linux-arm64.sha256
          - cross/bane-linux-amd64
          - cross/bane-linux-amd64.md5
          - cross/bane-linux-amd64.sha256
          - cross/bane-linux-386
          - cross/bane-linux-386.md5
          - cross/bane-linux-386.sha256
          - cross/bane-solaris-amd64
          - cross/bane-solaris-amd64.md5
          - cross/bane-solaris-amd64.sha256
          - cross/bane-windows-amd64
          - cross/bane-windows-amd64.md5
          - cross/bane-windows-amd64.sha256
          - cross/bane-windows-386
          - cross/bane-windows-386.md5
          - cross/bane-windows-386.sha256
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: "JISwosvCCw3O4FqbCr1cwMfa7wnQy1yrtmlkxXrgfnawWc1rJQHZr1oGNVapPOix+vUNiBCUFU3jFw74tOTmRkvH4ldlJd36TVr814gdfzIpX6Z5bGZJlJpR7MLBjJ7ETaWiGtTcLS7MwejIwqtCjgMwGp3h3iHO8c5BfRZQT9ZKkmZZn5hbfiFo1pxI9nkytMq2bSb8InUarZylgPAD2P0x4VRhgQxW+hpmex7yFSsi0R7dQjTD0dDPOu/Dls0XiocyG1wbMNjo3cQ+EsStwwPxI4MCUW+A/MPObcMWGOFaDhl6MrR3YclbXw0+O9GKljzoPNoMra1UgZG/fddWxMML1dzxCBBHeXwntTyE8pjMWbeRMHNomqoEABiZSoYPnCpE3Lsi1paCRw5JGiDeIWAVa46TiEQYkq1Ui3stkmjGeUtfd3TsXEFke50POfw5UP19eWD1onl1M3i0nJ01JPImMDwW3jP0k5hDMqQCGQPJRxe5k3lhVvOCi6ePcljlj2mPQf3OiPKsJUNKkmZ+EUOq78cys9vC0XRipG689pj5k6IP2Dv7s0DG8+wCg1Is1KaEzU6s4Tm17bFrPkNZ4o6Mye+KW4V4qv2duc9OyU5jmm8Sk09RFsnxWPSMG4mvGmDtsvRoDJa6RDkID5JfO6zNSunGs4hBKf65HcOtGeU="
